import java.util.List;

/**
 * Interface defining methods necessary to implement Rabin-Karp and
 * Boyer-Moore.
 */

public interface StringSearchingInterface {

    /**
     * Boyer Moore algorithm that relies on last table. Make sure to implement
     * the table before implementing this method. Works better with large
     * alphabets.
     *
     * If the pattern is null or of length 0, throw an IllegalArgumentException.
     * If the text is null, throw an IllegalArgumentException.
     * If the text is of length 0, return an empty list.
     *
     * @param pattern a CharSequence you are searching for in a body of text
     * @param text the body of text where you search for pattern
     * @return list of integers representing the first index a match occurs
     */
    public List<Integer> boyerMoore(CharSequence pattern, CharSequence text);

    /**
     * Builds last occurrence table that will be used to run the Boyer Moore
     * algorithm.
     *
     * Note that for a given char c will have an entry at table[c].
     * Each entry should be -1 if c is not in the pattern or the last index of c
     *
     * Ex. octocat
     *
     * table[o] = 3
     * table[c] = 4
     * table[t] = 6
     * table[a] = 5
     * table[everything else] = -1
     *
     * where c is a particular character in your pattern.
     *
     * HINT: Characters auto cast to their corresponding int in ASCII
     *
     * If pattern is null throw an IllegalArgumentException.
     *
     * @param pattern a CharSequence you are building last table for
     * @return integer array of size (Character.MAX_VALUE + 1) containing the
     * mapping for all characters in the ASCII
     */
    public int[] buildLastTable(CharSequence pattern);

    // prime base used for Rabin-Karp hashing, do NOT edit!!
    public static final int BASE = 433;

    /**
     * Hash function used for Rabin-Karp. The formula for hashing a string is:
     *
     * sum of: c * BASE ^ (pattern.length - 1 - i), where c is the integer
     * value of the current character, and i is the index of the character
     *
     * For example: Hashing "bunn" as a substring of "bunny" with base 433 hash
     * = b * 433 ^ 3 + u * 433 ^ 2 + n * 433 ^ 1 + n * 433 ^ 0 = 98 * 433 ^ 3 +
     * 117 * 433 ^ 2 + 110 * 433 ^ 1 + 110 * 433 ^ 0 = 7977892179
     *
     * If current is null throw an IllegalArgumentException.
     * If length is negative or greater than the length of current, throw an
     * IllegalArgumentException.
     *
     * @param current substring you are generating hash function for
     * @param length the length of the string you want to generate the hash for,
     * starting from index 0. For example, if length is 4, then you include
     * indices 0-3 in your hash (and pretend the actual length is 4)
     * @return hash of the substring
     */
    public int generateHash(CharSequence current, int length);

    /**
     * Updates a hash in constant time to avoid constantly recalculating
     * entire hash. To update the hash:
     *
     *  remove the oldChar times BASE raised to the length - 1, multiply by
     *  BASE, and add the newChar.
     *
     * For example: Shifting from "bunn" to "unny" in "bunny" with base 433
     * hash("unny") = (hash("bunn") - b * 433 ^ 3) * 433 + y * 433 ^ 0 =
     * (7977892179 - 98 * 433 ^ 3) * 433 + 121 * 433 ^ 0 = 9519051770
     *
     * @param oldHash hash generated by generateHash
     * @param length length of pattern/substring of text
     * @param oldChar character we want to remove from hashed substring
     * @param newChar character we want to add to hashed substring
     */
    public int updateHash(int oldHash, int length, char oldChar,
                          char newChar);

    /**
     * Runs Rabin-Karp algorithm. Generate initial hash, and compare it with
     * hash from substring of text same length as pattern. If the two
     * hashes match compare their individual characters, else update hash
     * and continue.
     *
     * If the pattern is null or of length 0, throw an IllegalArgumentException.
     * If the text is null, throw an IllegalArgumentException.
     * If the text is of length 0, return an empty list.
     *
     * @param pattern a string you a searching for in a body of text
     * @param text the body of text where you search for pattern
     * @return list of integers representing the first index a match occurs
     */
    public List<Integer> rabinKarp(CharSequence pattern, CharSequence text);
}
